server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: cidadania4u-ecossistema
    password: cidadania4u-ecossistema
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  rabbitmq:
    addresses: ${ENDENRECO_RABBIT}

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost