server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: cidadania4u-ecossistema
    password: cidadania4u-ecossistema
  jpa:
    properties:
      hibernate:
        time_zone: America/Sao_Paulo
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost